# Generated by Django 5.0.1 on 2024-06-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_product_photo_url_cart_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_carts', to='sale.product'),
        ),
    ]
